
services:
  # MongoDB Service
  mongodb:
    container_name: my_mongo_db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo:/data
    networks:
      - microservices-net
    restart: unless-stopped

  # Mongo Express (for managing MongoDB via web interface)
  mongo-express:
    container_name: my_mongo_express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: my_mongo_db
    networks:
      - microservices-net

  # PostgreSQL Service
  postgres:
    container_name: my_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: ${PGSQL_USERNAME}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped





networks:
  microservices-net:
    driver: bridge

volumes:
  mongo:
  postgres:
